/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SixRouteImport } from './routes/six'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SevenRouteImport } from './routes/seven'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as EightRouteImport } from './routes/eight'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SixDateRouteImport } from './routes/six_.$date'
import { Route as SevenDateRouteImport } from './routes/seven_.$date'
import { Route as EightDateRouteImport } from './routes/eight_.$date'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SixRoute = SixRouteImport.update({
  id: '/six',
  path: '/six',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SevenRoute = SevenRouteImport.update({
  id: '/seven',
  path: '/seven',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const EightRoute = EightRouteImport.update({
  id: '/eight',
  path: '/eight',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SixDateRoute = SixDateRouteImport.update({
  id: '/six_/$date',
  path: '/six/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const SevenDateRoute = SevenDateRouteImport.update({
  id: '/seven_/$date',
  path: '/seven/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const EightDateRoute = EightDateRouteImport.update({
  id: '/eight_/$date',
  path: '/eight/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eight': typeof EightRoute
  '/logout': typeof LogoutRoute
  '/seven': typeof SevenRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/six': typeof SixRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/eight/$date': typeof EightDateRoute
  '/seven/$date': typeof SevenDateRoute
  '/six/$date': typeof SixDateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eight': typeof EightRoute
  '/logout': typeof LogoutRoute
  '/seven': typeof SevenRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/six': typeof SixRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/eight/$date': typeof EightDateRoute
  '/seven/$date': typeof SevenDateRoute
  '/six/$date': typeof SixDateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/eight': typeof EightRoute
  '/logout': typeof LogoutRoute
  '/seven': typeof SevenRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/six': typeof SixRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/eight_/$date': typeof EightDateRoute
  '/seven_/$date': typeof SevenDateRoute
  '/six_/$date': typeof SixDateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eight'
    | '/logout'
    | '/seven'
    | '/signin'
    | '/signup'
    | '/six'
    | '/verify-email'
    | '/dashboard'
    | '/eight/$date'
    | '/seven/$date'
    | '/six/$date'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eight'
    | '/logout'
    | '/seven'
    | '/signin'
    | '/signup'
    | '/six'
    | '/verify-email'
    | '/dashboard'
    | '/eight/$date'
    | '/seven/$date'
    | '/six/$date'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/eight'
    | '/logout'
    | '/seven'
    | '/signin'
    | '/signup'
    | '/six'
    | '/verify-email'
    | '/_authed/dashboard'
    | '/eight_/$date'
    | '/seven_/$date'
    | '/six_/$date'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  EightRoute: typeof EightRoute
  LogoutRoute: typeof LogoutRoute
  SevenRoute: typeof SevenRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SixRoute: typeof SixRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  EightDateRoute: typeof EightDateRoute
  SevenDateRoute: typeof SevenDateRoute
  SixDateRoute: typeof SixDateRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/six': {
      id: '/six'
      path: '/six'
      fullPath: '/six'
      preLoaderRoute: typeof SixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seven': {
      id: '/seven'
      path: '/seven'
      fullPath: '/seven'
      preLoaderRoute: typeof SevenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eight': {
      id: '/eight'
      path: '/eight'
      fullPath: '/eight'
      preLoaderRoute: typeof EightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/six_/$date': {
      id: '/six_/$date'
      path: '/six/$date'
      fullPath: '/six/$date'
      preLoaderRoute: typeof SixDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seven_/$date': {
      id: '/seven_/$date'
      path: '/seven/$date'
      fullPath: '/seven/$date'
      preLoaderRoute: typeof SevenDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eight_/$date': {
      id: '/eight_/$date'
      path: '/eight/$date'
      fullPath: '/eight/$date'
      preLoaderRoute: typeof EightDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  EightRoute: EightRoute,
  LogoutRoute: LogoutRoute,
  SevenRoute: SevenRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SixRoute: SixRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  EightDateRoute: EightDateRoute,
  SevenDateRoute: SevenDateRoute,
  SixDateRoute: SixDateRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
